### ISSUE TITLE
Android7.0原生rom 点击我要发送闪退

### ISSUE THREAD

**Issue by mrrobot97** [mayubao/KuaiChuan#1]
复现率100%

**Comment by mayubao** [comment]
目前我还没适配android7.0的，可能是一些权限引起的问题。

**Comment by mrrobot97** [comment]
12-26 20:35:31.657 22634-22634/io.github.mayubao.kuaichuan E/linker: library "/system/lib/libqti_performance.so" ("/system/lib/libqti_performance.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
12-26 20:35:31.952 22634-22779/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                   Process: io.github.mayubao.kuaichuan, PID: 22634
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=22634, uid=10137 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                       at android.os.Parcel.readException(Parcel.java:1683)
                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                       at android.content.ContentResolver.query(ContentResolver.java:532)
                                                       at android.content.ContentResolver.query(ContentResolver.java:473)
                                                       at io.github.mayubao.kuaichuan.core.utils.FileUtils.getSpecificTypeFiles(FileUtils.java:96)
                                                       at io.github.mayubao.kuaichuan.ui.fragment.FileInfoFragment$GetFileInfoListTask.doInBackground(FileInfoFragment.java:195)
                                                       at io.github.mayubao.kuaichuan.ui.fragment.FileInfoFragment$GetFileInfoListTask.doInBackground(FileInfoFragment.java:175)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by mrrobot97** [comment]
请显示申请读写SD卡权限。

**Comment by mayubao** [comment]
@mrrobot97 已经适配了。我只是在模拟器上面跑了一下，你在真机上面看看有什么问题。
有问题再找我...
